spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring3_jpa_example?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: root99
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jwt:
    secret: xcloellspvjkqwejqjbbeuauqoegbhadkbcjhghugvqgueerhjwejkw